### ISSUE TITLE
Consider installing tools system-wide

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/template-python#68]
It seems like the dependencies installed by `$ make depends-ci` and `$make depends-dev` could be installed and used from the system Python to save time/space. In the `Makefile`, they could each be invoked by `$(SYS_PYTHON) -m <name`.

**Comment by jacebrowning** [comment]
@joshfriend Do you see any major issues with this?

**Comment by joshfriend** [comment]
I hand't noticed any slowness (probably because I'm using python2 and don't have to wait for `2to3` to convert the packages). I've also been pre-building wheels for stuff with compiled components like `lxml` and `psycopg2`, the telling `pip` to use those wheels by appending this to my shell init file:

```shell
export PIP_WHEEL_DIR=$HOME/.pip/wheelhouse
export PIP_FIND_LINKS=file://$PIP_WHEEL_DIR
```

But to specifically answer your question, no, I don't see anything wrong with that.

**Comment by jacebrowning** [comment]
@joshfriend Actually, this won't work because the system tools will know nothing of the virtually-installed packages they intent to lint, test. etc.
